### ISSUE TITLE
Websites eintragen / Icons Hauptmenü

### ISSUE THREAD

**Issue by alexplusde** [olien/redaxo-entwickler.de#12]
Hallo! Wie lassen sich denn aktuell Websites einpflegen? (Nächste Frage wäre, warum nicht die Referenzen auf redaxo.org dafür angezapft werden?)

Ist es außerdem gewollt, dass das Hauptmenü fast nur Fragezeichen-Icons hat?

**Comment by alexplusde** [comment]
Ich glaube, ich bin dir noch eine CSV schuldig :D

**Comment by olien** [comment]
Ach. Aktuell bin ich froh wenn ich nichts an der Seite machen muss... Wird eh irgendwann "sterben" und auf redaxo.org übertragen (ist noch ein superheftigwichtiges geheimnis)...

LG
Oliver 

(Ist gar kein Geheimnis... Nur geplant und nicht klar wann wir dazu kommen ;-)))

-- 
Via Handy

**Comment by alexplusde** [comment]
Okay, ich verrate es trotzdem keinem weiter! ;)
